/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface BTTBurnVaultInterface extends Interface {
  getFunction(
    nameOrSignature: "backingWithdraw" | "wbtcAddress"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "burnMade"): EventFragment;

  encodeFunctionData(
    functionFragment: "backingWithdraw",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "wbtcAddress",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "backingWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "wbtcAddress",
    data: BytesLike
  ): Result;
}

export namespace burnMadeEvent {
  export type InputTuple = [
    bttBurned: BigNumberish,
    wbtcWithdrew: BigNumberish
  ];
  export type OutputTuple = [bttBurned: bigint, wbtcWithdrew: bigint];
  export interface OutputObject {
    bttBurned: bigint;
    wbtcWithdrew: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BTTBurnVault extends BaseContract {
  connect(runner?: ContractRunner | null): BTTBurnVault;
  waitForDeployment(): Promise<this>;

  interface: BTTBurnVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  backingWithdraw: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  wbtcAddress: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "backingWithdraw"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "wbtcAddress"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "burnMade"
  ): TypedContractEvent<
    burnMadeEvent.InputTuple,
    burnMadeEvent.OutputTuple,
    burnMadeEvent.OutputObject
  >;

  filters: {
    "burnMade(uint256,uint256)": TypedContractEvent<
      burnMadeEvent.InputTuple,
      burnMadeEvent.OutputTuple,
      burnMadeEvent.OutputObject
    >;
    burnMade: TypedContractEvent<
      burnMadeEvent.InputTuple,
      burnMadeEvent.OutputTuple,
      burnMadeEvent.OutputObject
    >;
  };
}
